language: r
cache: packages

addons:
  apt:
    packages:
    - r-cran-rjava


before_install:
  - Rscript -e 'install.packages("rJava")'

r_packages:
  - rJava

warnings_are_errors: true

notifications:
  email:
  on_success: change
  on_failure: change
